### ISSUE TITLE
Unable to activate knife-xenserver-1.4.4, because chef-12.7.2 conflicts with chef (~> 11.18) 

### ISSUE THREAD

**Issue by fabio-santos-movile** [bvox/knife-xenserver#18]
```
$knife xenserver host list
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate knife-xenserver-1.4.4, because chef-12.7.2 conflicts with chef (~> 11.18) (Gem::ConflictError)
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in `activate'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /home/supergrilo/.chefdk/gem/ruby/2.1.0/gems/knife-xenserver-1.4.4/lib/chef/knife/xenserver_host_list.rb:18:in `<top (required)>'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:148:in `subcommand_class_from'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:209:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
    from /usr/bin/knife:50:in `load'
    from /usr/bin/knife:50:in `<main>'
```

**Comment by karlbaillie** [comment]
Experiencing this issue too :-1:

**Comment by nickkeyzer** [comment]
Same issue. Doesn't appear that this project is being worked on much anymore. 

```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate knife-xenserver-1.4.4, because chef-12.15.19 conflicts with chef (~> 11.18) (Gem::ConflictError)
```
